services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
      - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
